import {generateText} from 'ai';
import {NextResponse} from 'next/server';

export const runtime='nodejs';

type Family='null'|'repulsive_inverse_square'|'yukawa'|'oscillatory'|'quantum_postselected';
type Hypothesis={name:string;family:Family;summary:string;equation:string;parameters:string[];predictions:string[];falsification:string[];nuisance:string[];quantumApproach:string[]};

const families:Family[]=['null','repulsive_inverse_square','yukawa','oscillatory','quantum_postselected'];
function pickFamily(prompt:string):Family{const p=prompt.toLowerCase();if(p.includes('post')||p.includes('superposition')||p.includes('weak value')||p.includes('quantum gravity'))return 'quantum_postselected';if(p.includes('yukawa')||p.includes('range')||p.includes('fifth force'))return 'yukawa';if(p.includes('oscillat')||p.includes('periodic')||p.includes('frequency'))return 'oscillatory';if(p.includes('repuls')||p.includes('anti-grav')||p.includes('outward'))return 'repulsive_inverse_square';return 'repulsive_inverse_square';}
function fallback(prompt:string):Hypothesis{const family=pickFamily(prompt);const equations:Record<Family,string>={null:'a_obs = a_H0 + ε',repulsive_inverse_square:'a_X(r) = +α G M / r²',yukawa:'a_X(r) = +α G M r⁻² (1 + r/λ) exp(-r/λ)',oscillatory:'a_X(t) = A sin(2π f t + φ)',quantum_postselected:'A_w = <f|Â_g|i>/<f|i>;  a_Q = Re(A_w) - a_mix'};return {name:family==='quantum_postselected'?'Post-selected quantum-gravity residual':'Source-correlated anomalous-force candidate',family,summary:`Structured QAGRA fallback generated from the research prompt: ${prompt.slice(0,220)}${prompt.length>220?'…':''}`,equation:equations[family],parameters:['source mass M','source–probe separation r','coupling amplitude α or A','environmental nuisance coefficients','measurement-noise scale σ'],predictions:['Signal follows a predeclared mass/distance/time scaling law.','Signal reverses or disappears under at least one deliberate control chosen before data review.','Residual remains after electrostatic, magnetic, thermal, mechanical and analysis-bias models are fitted.'],falsification:['Blind sham configurations produce the same effect size.','The signal tracks voltage, temperature, vibration, magnetic field or apparatus orientation better than the proposed force law.','Independent replication fails at the sensitivity required to reproduce the claimed effect.'],nuisance:['electrostatic coupling','magnetic coupling','Casimir / surface forces','thermal gradients','vibration and acoustic pickup','geometry and calibration error'],quantumApproach:['Use quantum-feature or kernel models only against a strong classical baseline.','For source-superposition tests, simulate the source/probe Hamiltonian and post-selected conditional observable.','Export the discriminating circuit in OpenQASM and include state preparation, shots and readout in any advantage claim.']};}
function sanitize(value:any,prompt:string):Hypothesis{const fb=fallback(prompt);const family=families.includes(value?.family)?value.family:fb.family;const arr=(x:any,fbv:string[])=>Array.isArray(x)?x.filter(v=>typeof v==='string').slice(0,8):fbv;return {name:typeof value?.name==='string'?value.name.slice(0,140):fb.name,family,summary:typeof value?.summary==='string'?value.summary.slice(0,1200):fb.summary,equation:typeof value?.equation==='string'?value.equation.slice(0,900):fb.equation,parameters:arr(value?.parameters,fb.parameters),predictions:arr(value?.predictions,fb.predictions),falsification:arr(value?.falsification,fb.falsification),nuisance:arr(value?.nuisance,fb.nuisance),quantumApproach:arr(value?.quantumApproach,fb.quantumApproach)};}
function parseJson(text:string){const fenced=text.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]??text;const start=fenced.indexOf('{'),end=fenced.lastIndexOf('}');if(start<0||end<=start)throw new Error('No JSON object returned');return JSON.parse(fenced.slice(start,end+1));}

export async function POST(request:Request){
  let prompt='';try{const body=await request.json();prompt=String(body?.prompt||'').trim();}catch{return NextResponse.json({error:'Invalid JSON body.'},{status:400});}
  if(prompt.length<12)return NextResponse.json({error:'Describe the physical hypothesis in at least 12 characters.'},{status:400});
  if(prompt.length>6000)return NextResponse.json({error:'Prompt is too long.'},{status:400});
  const system=`You are the QAGRA hypothesis architect for a null-first gravity-research platform. Convert an idea into a falsifiable research hypothesis without claiming anti-gravity has been observed. Return JSON only with keys: name, family, summary, equation, parameters, predictions, falsification, nuisance, quantumApproach. family MUST be one of: null, repulsive_inverse_square, yukawa, oscillatory, quantum_postselected. Separate physical prediction from inference. Include conventional-force competitors and at least two decisive falsification tests. Quantum computation is an analysis/sensing method, not evidence by itself.`;
  try{
    const {text}=await generateText({model:'openai/gpt-5.6-sol',system,prompt:`Research idea:\n${prompt}\n\nReturn the JSON object only.`});
    return NextResponse.json({mode:'gateway',hypothesis:sanitize(parseJson(text),prompt)});
  }catch(error){
    return NextResponse.json({mode:'fallback',hypothesis:fallback(prompt),gatewayError:error instanceof Error?error.message:'Gateway unavailable'});
  }
}
