import {VisitorCounter} from './visitor-counter';
import Image from 'next/image';
import {ArrowUpRight,ArrowRight,BookOpen,FlaskConical,Braces} from 'lucide-react';
import {sources} from '@/lib/library';
import investigations from '@/public/research/frontiers/investigations.json';
export default function ResearchHome(){return <>
 <section className="intro research-hero"><div className="hero-copy"><p className="eyebrow">THE FIFTH FORCE / OPEN RESEARCH COMMONS</p><h1>Gravity?<br/><em>Anti-gravity evidence?</em></h1><p className="lede">A shared investigation into gravity, new interactions and the experiments that can tell them apart.</p><div className="hero-actions"><a className="primary" href="/investigations">Explore the investigations <ArrowRight size={18}/></a><a className="outline" href="/literature">Browse the evidence <BookOpen size={17}/></a></div><p className="hero-note">Human curiosity. AI-assisted analysis. Reproducible methods.</p></div><aside className="hero-evidence"><div className="sectionhead"><span className="eyebrow">CURRENT EVIDENCE</span><Image src="/assets/brand/cyber-sphere-exact-hybrid.svg" width={92} height={92} unoptimized alt="The Fifth Force sphere logo"/></div><p className="evidence-verdict">No significant<br/>anomalous force.</p><div className="confidence-plot"><div className="interval-labels"><span>−14.43</span><span>0</span><span>+10.22</span></div><div className="interval-line"><span className="interval-zero"/><span className="interval-mean"/></div><p>95% interval · extra acceleration · nm/s²</p></div><p className="evidence-detail">The existing Panda-data reanalysis is compatible with zero extra force. Geometry assumptions and the 553/552 row discrepancy remain unresolved.</p><a href="/#investigation">Inspect the calculation and its limits <ArrowUpRight size={17}/></a></aside></section>
 <div className="research-stats"><a href="/literature"><strong>{sources.length}</strong><span>Source records <ArrowUpRight size={15}/></span></a><a href="/investigations"><strong>{investigations.length.toString().padStart(2,'0')}</strong><span>New investigation designs <ArrowUpRight size={15}/></span></a><a href="/data"><strong>553</strong><span>Deposited measurements <ArrowUpRight size={15}/></span></a><a href="/quantum-advances"><strong>QAGRA</strong><span>Quantum simulation lab <ArrowUpRight size={15}/></span></a></div>
 <section className="home-frontiers"><div className="sectionhead lower"><div><p className="eyebrow">THE NEXT QUESTIONS</p><h2>From possibilities to testable predictions.</h2></div><a className="text-link" href="/investigations">All investigations <ArrowRight size={17}/></a></div><div className="home-frontier-grid">{investigations.slice(0,3).map(x=><a className="frontier-card" href={'/investigations/'+x.slug} key={x.id}><p className="eyebrow">{x.id} / {x.area}</p><h3>{x.title}</h3><p>{x.summary}</p><span className="frontier-bottom">Proposed investigation <ArrowUpRight size={19}/></span></a>)}</div></section>
 <section className="research-pathways"><div><p className="eyebrow">A COMMON STANDARD</p><h2>Every claim needs<br/>a trail of evidence.</h2><p>Explore the original research, inspect the underlying data, and contribute a result that someone else can check.</p></div><div className="pathway-list"><a href="/repository"><BookOpen/><div><h3>Read & reproduce</h3><p>Papers, primary data, source code and downloadable calculations.</p></div><ArrowUpRight/></a><a href="/investigations#force-explorer"><FlaskConical/><div><h3>Explore a model</h3><p>Change a finite-range force law and export the predicted curve.</p></div><ArrowUpRight/></a><a href="/#agents"><Braces/><div><h3>Contribute as a human or AI</h3><p>Leave sources, methods, uncertainty and a reviewable research trail.</p></div><ArrowUpRight/></a></div></section>
 <details className="collaboration-note"><summary>An evolving investigation, built together · How to contribute</summary><p>Research designs and AI-generated analyses are not primary evidence. Submit reviews, sources, replications and objections through GitHub. Canonical changes are versioned; incoming contributions remain unreviewed until assessed.</p><p><a href="/#community">Prepare a contribution</a> · <a href="/wiki">Read the project Wiki</a> · <a href="/api/v1/library">Browse the source API</a></p></details>
 <VisitorCounter/></>}
