'use client';
import {useState} from 'react';
import {Download,RotateCcw} from 'lucide-react';
import {yukawaCorrection} from '@/lib/force-law';
export default function ForceExplorer(){
 const[alpha,setAlpha]=useState(.2),[range,setRange]=useState(100);
 const rows=Array.from({length:101},(_,i)=>{const r=10**(i/50+1);return {separation_um:r,correction:yukawaCorrection(alpha,range,r)}});
 const coords=rows.map((p,i)=>`${60+i*5.8},${150-p.correction*110}`).join(' ');
 function download(){const text='separation_um,delta_force_over_newtonian\n'+rows.map(p=>p.separation_um+','+p.correction).join('\n'),u=URL.createObjectURL(new Blob([text],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download=`yukawa-model-alpha-${alpha}-lambda-${range}um.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 return <section className="force-lab" id="force-explorer"><div className="sectionhead"><div><p className="eyebrow">INTERACTIVE MODEL / NOT MEASURED DATA</p><h2>What would a finite-range correction look like?</h2></div><span className="tag">Point-mass benchmark</span></div><div className="force-layout"><div className="force-controls"><label htmlFor="coupling">Relative coupling α <output>{alpha.toFixed(2)}</output></label><input id="coupling" type="range" min="-1" max="1" step="0.05" value={alpha} onChange={e=>setAlpha(Number(e.target.value))}/><label htmlFor="range">Interaction range λ <output>{range} μm</output></label><input id="range" type="range" min="10" max="500" step="10" value={range} onChange={e=>setRange(Number(e.target.value))}/><p className="force-formula">ΔF / Fₙ = α(1 + r/λ)e⁻ʳ⁄λ</p><p>Positive values add attraction. Negative values reduce attraction; they do not necessarily reverse the total force.</p><button className="text-button" onClick={()=>{setAlpha(.2);setRange(100)}}><RotateCcw size={15}/>Reset parameters</button></div><div><svg className="force-chart" viewBox="0 0 700 325" role="img" aria-label={`Yukawa force correction versus separation. Coupling ${alpha}, range ${range} micrometres. Theoretical curve only.`}>{[-1,-.5,0,.5,1].map(v=><g key={v}><line x1="60" x2="640" y1={150-v*110} y2={150-v*110} stroke={v===0?'#a0b3c5':'#263747'} strokeDasharray={v===0?'5 5':undefined}/><text x="45" y={155-v*110} textAnchor="end" fill="#b5c4d2" fontSize="14">{v}</text></g>)}{[10,100,1000].map((r,i)=><g key={r}><line x1={60+i*290} x2={60+i*290} y1="40" y2="260" stroke="#263747"/><text x={60+i*290} y="286" textAnchor="middle" fill="#b5c4d2" fontSize="14">{r}</text></g>)}<text x="60" y="22" fill="#b5c4d2" fontSize="14">Signed correction / Newtonian force</text><polyline points={coords} fill="none" stroke="#b5f56b" strokeWidth="3"/><text x="350" y="315" textAnchor="middle" fill="#b5c4d2" fontSize="14">Separation r (μm) · logarithmic scale</text></svg><p className="model-readout" aria-live="polite">At r = λ: correction = {(yukawaCorrection(alpha,range,range)*100).toFixed(2)}% of Newtonian attraction.</p></div></div><div className="sectionhead"><p className="fine">No apparatus geometry, screening, uncertainty, or experimental exclusions are included. Parameters are illustrative and may be excluded by real experiments.</p><button className="outline" onClick={download}><Download size={16}/>Export model CSV</button></div></section>
}
