export const areas=[{id:'theory',title:'Theoretical models',description:'Actions, field equations, conservation laws, screening and stability. A mathematical solution needs a realizable physical source.'},{id:'experiment',title:'Physics tests & laboratory research',description:'Measurements, calibration, apparatus geometry, uncertainties and independent replication.'},{id:'engineering',title:'Engineering & physical devices',description:'Sensors, materials, fabrication and controlled prototypes. Conventional force balance must be distinguished from modifying gravity.'}];
export const institutions=[
{id:'saifr',name:'ICTP-SAIFR / IFT-UNESP',region:'Brazil',area:'theory',url:'https://www.ictp-saifr.org/gravityprize/',focus:'Classical-gravity research and a regional network of theoretical physicists.'},
{id:'uct',name:'University of Cape Town · Cosmology and Gravity',region:'South Africa',area:'theory',url:'https://uctcosmology.com/',focus:'Cosmology, extended gravity and gravitational-wave physics.'},
{id:'eotwash',name:'Eöt-Wash · University of Washington',region:'United States',area:'experiment',url:'https://www.npl.washington.edu/eotwash/publications',focus:'Torsion balances, equivalence principle and fifth-force constraints.'},
{id:'berkeley',name:'Müller Group · UC Berkeley',region:'United States',area:'experiment',url:'https://matterswaves.com/',focus:'Atom interferometry and precision gravity measurements; source of the Panda dataset.'},
{id:'cern',name:'CERN · ALPHA',region:'Switzerland / international',area:'experiment',url:'https://home.cern/alpha-experiment-at-cern-observes-the-influence-of-gravity-on-antimatter/',focus:'Antihydrogen gravity measurements. Observed attraction is not antimatter levitation.'},
{id:'perimeter',name:'Perimeter Institute',region:'Canada',area:'theory',url:'https://perimeterinstitute.ca/research/research-areas/quantum-gravity',focus:'Multiple approaches to quantum gravity and spacetime.'},
{id:'aei',name:'Max Planck · Albert Einstein Institute',region:'Germany',area:'theory',url:'https://www.aei.mpg.de/',focus:'Relativity, quantum gravity, computation and gravitational-wave research.'},
{id:'vienna',name:'Aspelmeyer Group · IQOQI Vienna',region:'Austria',area:'experiment',url:'https://www.iqoqi-vienna.at/research/aspelmeyer-group',focus:'Experiments at the interface of quantum physics and gravity.'},
{id:'qgi',name:'Ben-Gurion / Ulm / Oxford collaboration',region:'Israel / Germany / United Kingdom',area:'experiment',url:'https://www.ox.ac.uk/news/2026-08-28-scientists-observe-einsteins-gravity-in-the-quantum-world',focus:'Quantum free-fall phase measurements and equivalence-principle tests.'},
{id:'cug',name:'China University of Geosciences · gravity tests',region:'China',area:'experiment',url:'https://en.cug.edu.cn/info/1228/2686.htm',focus:'Laboratory inverse-square-law tests at millimeter and centimeter scales.'},
{id:'anu',name:'ANU Centre for Gravitational Astrophysics / OzGrav',region:'Australia',area:'engineering',url:'https://cga.anu.edu.au/about',focus:'Gravitational-wave instrumentation, source modeling and precision detection.'},
{id:'kagra',name:'ICRR · University of Tokyo / KAGRA',region:'Japan',area:'engineering',url:'https://www.icrr.u-tokyo.ac.jp/',focus:'Gravitational-wave observation and cryogenic detector technology.'},
{id:'gwosc',name:'Gravitational Wave Open Science Center',region:'International',area:'experiment',url:'https://gwosc.org/',focus:'Public gravitational-wave data and reproducible analysis resources.'}
];
export const updates=[
{id:'quantumrepulsion2026',title:'Conditional quantum repulsion: a proposal to test',area:'theory',date:'2026-07-20',source:'https://arxiv.org/abs/2602.12266',institution:'UFMG / Oxford · Saldanha, Marletto & Vedral',evidence:'Theoretical preprint; full HTML checked',summary:'A spatially superposed source mass and postselection can produce a repulsive conditional probe momentum shift in the proposed quantum model.',limit:'This is not a demonstrated gravitational device. Selected outcomes must be evaluated alongside rejected outcomes and the success probability.',next:'Compute the exact conditional and unconditional momentum distributions, then include decoherence and detector noise before estimating experimental sensitivity.'},
{id:'vector2025',title:'A new vector-field constraint for the research register',area:'experiment',date:'2025-10-13',source:'https://arxiv.org/abs/2510.21764',institution:'Eöt-Wash',evidence:'Author preprint / abstract checked',summary:'A rotating torsion-balance search probes ultralight vector dark matter coupled to baryon minus lepton number. It reports a peak coupling limit of 9 × 10⁻²⁶ over a searched mass range of 1.3 × 10⁻²² to 1.9 × 10⁻¹⁸ eV.',limit:'These are dark-matter-search constraints under the paper’s assumptions; they cannot be applied unchanged to a laboratory screened controller.',next:'Read the full likelihood and environmental assumptions before updating the screened-vector parameter scan.'},
{id:'qgi2026',title:'Quantum free fall provides a new experimental benchmark',area:'experiment',date:'2026-09-03',source:'https://www.science.org/doi/10.1126/sciadv.aec8045',institution:'Ben-Gurion / Ulm / Oxford',evidence:'Institutional report checked; linked journal paper',summary:'An atom-chip interferometer compares held and freely falling atomic wavepackets. The measured phase is consistent with the equivalence principle in the tested quantum regime.',limit:'This does not establish quantum gravity or gravity control. Magnetic support of one wavepacket is an ordinary applied force.',next:'Retrieve the paper’s methods, data and covariance before attempting independent calibration.',context:'https://www.ox.ac.uk/news/2026-08-28-scientists-observe-einsteins-gravity-in-the-quantum-world'},
{id:'horizon2026',title:'Black-hole signals as a test of strong gravity',area:'theory',date:'2026-06-25',source:'https://www.ozgrav.org/news/scientists-find-a-way-to-study-the-event-horizon-where-light-sound-are-swallowed-for-eternity/',institution:'OzGrav / ANU',evidence:'Institutional research report',summary:'Researchers report using a direct-wave component of GW250114 to investigate properties of a remnant black-hole horizon.',limit:'This is an observational probe of strong gravity, not an engineering mechanism for controllable repulsion.',next:'Trace the linked research paper and public strain data; compare its model assumptions with independent analyses.'},
{id:'panda2024',title:'Reproduce a real fifth-force measurement',area:'engineering',date:'2024-06-26',source:'https://doi.org/10.5281/zenodo.10995225',institution:'UC Berkeley / Panda et al.',evidence:'Released data independently fitted in this repository',summary:'Our fit to 553 released acceleration rows gives an extra-force estimate of −2.10 ± 6.29 nm/s², consistent with zero.',limit:'The 553/552 row discrepancy and missing metrology remain unresolved; our geometry and spectrum are limited benchmarks.',next:'Contribute a checksum-verified replication or recover the missing geometry and covariance.'}
];
export const videos=[
{id:'tyson',title:'The Mysterious Force of Gravity Explained by Neil deGrasse Tyson',creator:'Science Time / Neil deGrasse Tyson',url:'https://www.youtube.com/watch?v=ybxSgIBbBh8',area:'theory',status:'Video metadata checked; caption endpoint returned no text',lesson:'Educational discussion of gravity. No transcript or specific spoken claim is verified here; use primary experiments for research conclusions.'},
{id:'sabine',title:'Scientists Have Figured Out How to Make Antigravity',creator:'Sabine Hossenfelder',url:'https://www.youtube.com/watch?v=XKRMbVpJ3Rc&t=160s',area:'theory',status:'Description links arXiv:2602.12266; paper checked; captions unavailable',lesson:'The underlying source is a conditional quantum-repulsion proposal. The 2:40 link is the supplied viewing bookmark, not a verified claim timestamp. See the quantum-repulsion research update above.'},
{id:'greenglow',title:'Project Greenglow: Is Gravity Control Actually Possible?',creator:'Spark',url:'https://www.youtube.com/watch?v=JMWEQwIt_ew',area:'engineering',status:'Video title and description checked; captions unavailable',lesson:'Historical research lead. Compare the program narrative with NASA technical reports and controlled replication results before adopting a proposed mechanism.'},
{id:'cox',title:'What Bothers Physicists About Black Holes (Interview with Brian Cox)',creator:'Cleo Abram / Brian Cox',url:'https://www.youtube.com/watch?v=bY1EQ6HD-ao',area:'theory',status:'YouTube title and creator verified via oEmbed; full transcript not verified',lesson:'Use as a starting point for questions about black holes and quantum gravity. Extract timestamped claims and link primary papers before treating any statement as research evidence.'},
{id:'alpha',title:'ALPHA-g observes the influence of gravity on antimatter',creator:'CERN video archive',url:'https://videos.cern.ch/record/2298313',area:'experiment',status:'Official video record checked; not a frame-by-frame review',lesson:'Pair the institutional video with the experimental paper and uncertainty budget. Antihydrogen attraction does not demonstrate gravity control.'},
{id:'perimetervideo',title:'Perimeter public lectures and research explainers',creator:'Perimeter Institute',url:'https://www.youtube.com/@PIOutreach/videos',area:'theory',status:'Official channel directory; individual videos require review',lesson:'Prioritize lectures with named researchers, equations and linked publications. An institute’s reputation does not validate every interpretation.'}
];
