import {notFound} from 'next/navigation';
import investigations from '@/public/research/frontiers/investigations.json';
import {sources} from '@/lib/library';
import {SiteNavigation} from '../../site-navigation';
import Markdown from '../../markdown';
import {ArrowLeft,ArrowUpRight,Download} from 'lucide-react';
import {contributionUrl} from '@/lib/github';
export function generateStaticParams(){return investigations.map(x=>({slug:x.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const x=investigations.find(x=>x.slug===slug);return {title:x?x.title+' | Open Field':'Investigation not found'}}
export default async function Investigation({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const x=investigations.find(x=>x.slug===slug);if(!x)notFound();const refs=sources.filter(s=>x.sources.includes(s.id));return <main><SiteNavigation current="frontiers"/><div className="reader-toolbar"><a href="/investigations" className="outline"><ArrowLeft size={16}/>All investigations</a><a className="outline" href={'/research/frontiers/'+x.slug+'.md'} download><Download size={16}/>Download Markdown</a></div><section className="dossier-heading"><p className="eyebrow">{x.id} / {x.area} / {x.date}</p><h1>{x.title}</h1><p className="lede">{x.summary}</p></section><div className="research-notice">{x.status} · AI-assisted research design · Not peer reviewed · No new experimental result</div><div className="frontier-reader"><article className="paper"><Markdown content={x.body}/><h2 id="sources">Read the supporting documentation</h2><p>Sources support the background and methods. They do not validate this proposed investigation.</p>{refs.map(s=><div className="dossier-source" key={s.id}><a href={'/literature/'+s.id}>{s.id} · {s.topic} <ArrowUpRight size={15}/></a><p>{s.year} · {s.evidence}</p></div>)}</article><aside className="dossier-aside"><p className="eyebrow">INVESTIGATION RECORD</p><h3>What moves this forward?</h3><p>Independent derivation, a calibrated dataset, a reproducible implementation, or a well-supported objection.</p><a className="primary" href={contributionUrl({kind:'review',title:x.id+': '+x.title,task:x.id,body:'Investigation: '+x.title+'\n\nMethod or objection:\n\nPrimary sources:\n\nResults and uncertainty:\n\nReproducibility details:\n',agent:'Specify human / AI assistance'})}>Prepare a review <ArrowUpRight size={16}/></a><p className="fine">Opens a GitHub draft. Review and submit there; it is not automatically accepted as evidence.</p><a href={'/literature?q='+encodeURIComponent(x.sources[0])}>Inspect source metadata</a><a href="/quantum-advances">Open Quantum Advances</a><a href="/data">Inspect experimental data</a></aside></div></main>}
