'use client';
import {useEffect,useState} from 'react';
import {SiteNavigation} from '../site-navigation';
import {Input} from '@/components/ui/input';
import {Search,ArrowUpRight,Download,Library} from 'lucide-react';
import {sources,searchSources} from '@/lib/library';
import {ReferenceContributions} from './submissions';
const categories=[...new Set(sources.map(x=>x.category))].sort();
const evidenceTypes=[...new Set(sources.map(x=>x.evidence))].sort();
export default function Literature(){
 const[q,setQ]=useState(''),[category,setCategory]=useState(''),[evidence,setEvidence]=useState(''),[sort,setSort]=useState('register'),[page,setPage]=useState(0);
 useEffect(()=>{setQ(new URLSearchParams(location.search).get('q')||'')},[]);
 const filtered=searchSources(q,category,evidence,sort),pages=Math.max(1,Math.ceil(filtered.length/12));
 function reset(){setQ('');setCategory('');setEvidence('');setSort('register');setPage(0)}
 function exportResults(){const b=new Blob([JSON.stringify(filtered,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='open-field-literature-selection.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 return <main><SiteNavigation current="literature"/><section className="page-heading"><div><p className="eyebrow">THE EVIDENCE LIBRARY</p><h1>Literature register</h1><p className="lede">Trace the claim. Read the source. Understand the limitation.</p></div><a className="primary" href="#submit-reference">Add a reference <ArrowUpRight size={17}/></a></section>
 <div className="library-summary"><Library size={24}/><strong>{sources.length} source records</strong><span>20 newly annotated primary records</span><a href="/research/literature.json" download>Complete JSON <Download size={15}/></a></div>
 <section className="library-tools" aria-label="Filter source library"><label className="search"><Search size={20}/><Input value={q} onChange={e=>{setQ(e.target.value);setPage(0)}} placeholder="Search title, author, source ID, claim or limitation…" aria-label="Search literature"/></label><div className="filter-row"><label>Research field<select value={category} onChange={e=>{setCategory(e.target.value);setPage(0)}}><option value="">All fields</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Evidence type<select value={evidence} onChange={e=>{setEvidence(e.target.value);setPage(0)}}><option value="">All types</option>{evidenceTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Sort by<select value={sort} onChange={e=>{setSort(e.target.value);setPage(0)}}><option value="register">Register order</option><option value="newest">Newest publication</option><option value="oldest">Oldest publication</option></select></label><button className="outline" onClick={reset}>Clear filters</button></div></section>
 <div className="sectionhead source-count"><p role="status">{filtered.length} matching sources</p><button className="text-button" onClick={exportResults}><Download size={16}/>Export these results</button></div>
 <div className="literature">{filtered.slice(page*12,page*12+12).map(x=><article key={x.id} id={x.id}><div className="source-meta"><span className="eyebrow">{x.id} / {x.year}</span><span className="tag">{x.evidence}</span></div><h3><a href={x.source} target="_blank" rel="noopener noreferrer">{x.topic} <ArrowUpRight size={17}/></a></h3>{x.authors&&<p className="source-authors">{x.authors}</p>}<p>{x.result}</p><div className="source-field">{x.category}</div><details><summary>Assessment, limitations & next check</summary><p><strong>Record status:</strong> {x.status}</p><p><strong>Common error:</strong> {x.common_error}</p><p><strong>Required check:</strong> {x.correction}</p><p><strong>Review scope:</strong> {x.review_scope||'Inherited annotation; not re-audited in the September 2026 expansion.'}</p>{x.reviewed_on&&<p>Record checked {x.reviewed_on}. {x.replication}.</p>}{x.investigations?.map(slug=><a className="source-dossier" href={'/investigations/'+slug} key={slug}>Related investigation: {slug.replaceAll('-',' ')} ↗</a>)}</details></article>)}</div>
 {!filtered.length&&<div className="empty"><h2>No sources match these filters.</h2><p>Try an author, a source ID such as SRC-077, or a broader physics term.</p><button className="outline" onClick={reset}>Show all sources</button></div>}
 <div className="data-controls"><button className="outline" disabled={!page} onClick={()=>setPage(page-1)}>Previous sources</button><span>Page {page+1} / {pages}</span><button className="outline" disabled={page+1>=pages} onClick={()=>setPage(page+1)}>Next sources</button></div><p className="fine">Primary-record checks cover the linked abstract or landing page, not an independent experimental replication. Imported annotations retain their original status. The archived Rev02 workbook is a separate historical snapshot.</p><ReferenceContributions/></main>
}
